In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a = tf.constant(15)
b = tf.constant(20)
print(a + b)

tf.Tensor(35, shape=(), dtype=int32)


In [3]:
x = np.random.rand(100).astype(np.float32)
print(x)

[8.5747600e-01 5.9346712e-01 4.0475410e-01 3.3663526e-01 6.5755123e-01
 8.9977950e-01 6.2277323e-01 3.9244112e-01 2.8932667e-01 6.5145758e-03
 8.0949354e-01 6.5807915e-01 5.8506119e-01 4.6526501e-01 8.5753947e-02
 7.6921588e-01 1.8521525e-01 2.4525627e-01 7.7422792e-01 6.7181122e-01
 8.6627282e-02 5.2926499e-01 8.1403106e-01 4.8795900e-01 1.9668347e-01
 7.6690304e-01 8.4842943e-02 9.9702649e-02 6.8638146e-01 2.1087699e-01
 5.1972336e-01 1.5570214e-01 2.1521549e-01 4.2266411e-01 4.7001275e-01
 1.8186383e-01 1.0492758e-01 8.9891858e-02 7.7093679e-01 1.3713618e-01
 5.2636999e-01 8.2313709e-02 2.7360401e-01 6.3308126e-01 8.6643559e-01
 2.0973559e-01 4.2572066e-01 2.8922179e-01 4.5154011e-01 6.0331625e-01
 3.9960024e-01 5.9421003e-01 6.1037672e-01 3.1317648e-01 1.7508110e-02
 5.3826574e-02 7.1543097e-01 9.4262129e-01 6.4502090e-01 5.8742851e-01
 5.8060473e-01 4.4179684e-01 9.1305360e-02 6.5882123e-01 8.9081430e-01
 5.6935811e-01 4.8677161e-04 4.0921059e-01 5.8030581e-01 2.2441166e-02
 7.663

In [4]:
y = x * 0.2 + 0.2

In [5]:
w = tf.Variable(tf.random.normal([1]))

In [6]:
b = tf.Variable(tf.zeros([1]))

In [7]:
def mse_loss():
  ypred = w * x + b
  loss = tf.reduce_mean(tf.square(ypred - y))
  return loss

In [8]:
optimizer = tf.keras.optimizers.Adam()

In [9]:
for step in range(5000):
  optimizer.minimize(mse_loss, var_list=[w, b])
  if step % 500 == 0:
    print(step, w.numpy(), b.numpy())

0 [1.6033554] [-0.001]
500 [1.2452198] [-0.28053984]
1000 [1.0443071] [-0.2289823]
1500 [0.84337693] [-0.1267104]
2000 [0.6487285] [-0.02745806]
2500 [0.48116553] [0.05764987]
3000 [0.35373875] [0.1222152]
3500 [0.2704263] [0.16437717]
4000 [0.22561316] [0.18704541]
4500 [0.20690021] [0.19651008]


In [10]:
import torch
import numpy as np

In [11]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(type(x_data))

<class 'torch.Tensor'>


In [12]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)
print(type(x_np))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>


In [13]:
x_ones = torch.ones_like(x_data)
print("One Tensor:\n", x_ones)
x_rand = torch.rand_like(x_data, dtype = torch.float)
print(x_rand)

One Tensor:
 tensor([[1, 1],
        [1, 1]])
tensor([[0.1676, 0.1018],
        [0.2413, 0.2710]])


In [14]:
shape = (2, 3)
random_tensor = torch.rand(shape)
print(random_tensor)
print(type(random_tensor))
ones_tensor = torch.ones(shape)
print(ones_tensor)
print(type(ones_tensor))
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)
print(type(zeros_tensor))
tensor = torch.rand(3, 4)
print(tensor)
tensor.shape
tensor.dtype
tensor.device

tensor([[0.7904, 0.5637, 0.5165],
        [0.1162, 0.1070, 0.0727]])
<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[0.4183, 0.5422, 0.9171, 0.1475],
        [0.4032, 0.6472, 0.8144, 0.9705],
        [0.7077, 0.6623, 0.5036, 0.0807]])


device(type='cpu')

In [15]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print("Device tensor is stored in ", tensor.device)

In [16]:
tensor = torch.ones(4, 4)
print("Tensor:\n", tensor)
tensor1 = torch.zeros(4, 4)
print("Tensor1:\n", tensor1)
tensor2 = torch.cat([tensor, tensor1])
print("Tensor2:\n", tensor2)

Tensor:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Tensor1:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Tensor2:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [17]:
tensor.mul(tensor1)
tensor * tensor1
tensor.T

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
tensor.add_(3)
print(tensor)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [19]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)
print(type(n))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
